### ISSUE TITLE
dead or alive? 

### ISSUE THREAD

**Issue by JDJoe** [hatzkel/TradingViewCAT#3]
dead or alive? 

EDIT:
OK, I see, this is just a copy/paste of https://github.com/Robswc/tradingview-webhooks-bot/

**Comment by hatzkel** [comment]
Yeah it's a fork with some changes so that it would work at the time of fork it was having issues. I believe it has since been updated. Personally I've just been using 3commas for order handling. https://3commas.io/?c=tc168483

I never got around to implementing safety trading in this which was my intention. (Pyramiding orders when price moved against entry to either exit in profit rather than loss and or reduce/increase(long or short) entry and liquidation price.

Feel free to join my telegram channel if you have any questions https://t.me/tophatcrypto

**Comment by JDJoe** [comment]
I was attempting to join but got a error message something about no such user or group. 
It seems that Robswc is gone missing too. 
Personally cant write any code :) so I keep searching a project that can meet my needs but so far, nothing. 
3commas is nice but last time I checked, it has no support for Kraken.

**Comment by hatzkel** [comment]
Kraken is horrible for slippage anyway, you don't want to be trading on Kraken. Give bybit a try. 
 https://www.bybit.com/app/register?ref=DQJx6

I personally use coinbase as an onramp/exit ramp and bybit for trading.

**Comment by hatzkel** [comment]
Message me directly on telegram. @hatzkel

**Comment by JDJoe** [comment]
I dropped by your Telegram group few days ago. It's absolute rubbish what you tell those people over there. I guess it's all about getting them signed up to those services you peddle so you can get your kickback.
